name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install
      run: npm install

    - name: build
      env:
        NODE_ENV: production
      run: npm run build

    - name: deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
